
server:
  port: 8081 #${PORT:0}
spring:
  application:
    name: service-Account
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Account

eureka:
  client:
  service-url:
  defaultZone: http://localhost:8761/eureka
